name: Ejemplo servicios

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: test
        ports:
          - 3306:3306

    steps:
      - name: LS
        run: ls -al