name: Test

on:
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ls
        run: |
          chmod +x script.sh
          ./script.sh
      - name: myAction
        uses: ./.github/actions/myAction