name: Test composite actions

on:
  push:
    branches:
      - main

jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: ReuseAction
        uses: ./.github/actions/myAction
        with:
          message: "Prueba 1"